### ISSUE TITLE
Can't get even the example projects to work

### ISSUE THREAD

**Issue by Noxime** [digitalspider/jlxd#1]
Maybe I am missing something, but I cannot get the library (or even jlxd-cli) to work. I do not get any errors, everything looks to work fine, but nothing actually happens.

```Java
ILxdService api = new LxdServiceImpl();
ILxdApiService lxdApiService = new LxdApiServiceImpl();
ILinuxCliService linuxCliService = new LinuxCliServiceImpl();
lxdApiService.setLinuxCliService(linuxCliService);
api.setLxdApiService(lxdApiService);

api.createContainer("container_name", "images:alpine/edge");
```

outputs
```
2017-10-28 14:54:19 INFO  LxdApiServiceImpl:324 - repsonse=OperationResponse: type=async, status=Operation created, statusCode=100, metadata=Operation{id='326d330a-c190-4c29-b6b4-28c55cda92df', classType='task', createdDate='2017-10-28T14:54:19.26748073+03:00', updatedDate='2017-10-28T14:54:19.26748073+03:00', status='Running', statusCode='103', resources='{containers=[/1.0/containers/327592088315363328]}', metadata='null', mayCancel='null', err=''}, error=, errorCode=0
```
, but nothing happens (container should show up when doing `lxc list`)

any further operations (like `api.startContainer("container_name");`) causes an error with
```
java.lang.IllegalArgumentException: container: container_name has state null
	at au.com.jcloud.lxd.service.impl.LxdServiceImpl.changeContainerState(LxdServiceImpl.java:125)
	at au.com.jcloud.lxd.service.impl.LxdServiceImpl.startContainer(LxdServiceImpl.java:141)
```

And as earlier stated, even example project `Jlxd-cli` fails to work. No errors, just nothing happens. Strangely enough, the webapp `Jlxd-ui` works fine, but I can't figure out why.

Any assistance?

System info:
Lxd version: 2.18
Ubuntu version: 17.10

**Comment by digitalspider** [comment]
Hi, sorry for the late reply. I have been working on other projects recently. I think you are right, since I've added a lot of new features to the jlxd-ui part of the app, I did not go back and retest the jlxd-cli part. Will check this out and have a look over the next week or so. Sorry for the inconvenience.

**Comment by schulzlu** [comment]
If you're still working on that @Noxime I just created another issue that is explaining a bit why you could have some problems. 
After you make those changes it should work, at least for me it does. 😄
